### ISSUE TITLE
STRING download failed

### ISSUE THREAD

**Issue by vincent-van-hoef** [C3c6e6/SetRank_interactomes#1]
Hello,

First of all thanks for this nice package! I have however a problem with downloading the data from STRING. When running make, this error appears:

Makefile:13: recipe for target 'data/protein.links.detailed.v10.txt.gz' failed
make: *** [data/protein.links.detailed.v10.txt.gz] Error 8

Seems like a version issue, because STRING is now on v10.5. Changing the makefile did not work however, so I'm probably missing something. Thanks!

**Comment by C3c6e6** [comment]
Dear Vincent!

Thanks for letting me know, I have fixed the problem!

Best,
Cedric

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

-------- Original Message --------
